version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.16.0
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run:
          name: Install Dependencies
          command: |
            npm install
      - save_cache:
          paths:
            - ./node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Build
          command: |
            npm run build
      - run:
          name: Test
          command: |
            npm run test:ci
      - run:
          name: Lint
          command: |
            npm run lint
      - run:
          name: Move Assets
          command: |
            mkdir -p dist/assets/
            cp cfn/* dist/assets/
            cp -r www dist/assets/

      - persist_to_workspace:
          root: dist
          paths:
            - assets

  release:
    docker:
      - image: circleci/python:2.7-jessie
    working_directory: ~/tmp
    steps:
      - run:
          name: Install awscli
          command: sudo pip install awscli
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Check Workspace Again
          command: ls -ll /tmp/workspace/assets
      - run:
          name: Setup Credentials
          command: |
                mkdir ~/.aws
                mv /tmp/workspace/assets/aws_config ~/.aws/config
                echo "[default]" > ~/.aws/credentials
                echo "aws_access_key_id = ${AWS_ACCESS_KEY_ID}" >> ~/.aws/credentials
                echo "aws_secret_access_key = ${AWS_SECRET_ACCESS_KEY}" >> ~/.aws/credentials
      - run:
          name: Deploy
          command: |
                cd /tmp/workspace/assets
                deploy.sh pain-logger dev
                aws s3 sync /tmp/workspace/assets/www s3://pain-logger-dev-446226631021/

workflows:
  version: 2
  test_and_release:
    jobs:
      - build
      - release:
          requires:
            - build
          filters:
            branches:
              only: master